### ISSUE TITLE
funtion `runifint` is absent

### ISSUE THREAD

**Issue by massisenergy** [bertcarnell/lhs#20]
I installed the `lhs` package from both `CRAN` & `devtools::github` (`Rstudio` in `Windows 10` & `MacOS 10.14`, but none of the installations provided me the function `runifint()`, which can be used when the output of latin hypercube design needs to be integer numbers, mentioned at the end of the documentation of the package.

Thanks for your useful package (in other instances) of course!

**Comment by bertcarnell** [comment]
Good question.  You can access that function using the `:::` operator because it is not an exported function.  `lhs:::runifint(10, 1, 3)`
It does not create an integer-based Latin hypercube, however.  For that, see the FAQ vignette in the lhs package.  `utils::browseVignettes()`
I will work on eliminating the `runifint` function from the docs so it is not confusing.

**Comment by bertcarnell** [comment]
I changed my mind and decided to export the function in the next version.  Entered in https://github.com/bertcarnell/lhs/commit/f803c4d6d6c7f11e89a047bd8d109bcc8c2282ab
