### ISSUE TITLE
Bug in createAddelKempN

### ISSUE THREAD

**Issue by ugroempi** [bertcarnell/lhs#25]
Hi Rob,

thank you for providing access to the classical orthogonal array creation methods from Owen's C code. I just encountered a bug, however: `createAddelKempN` apparently does not always create an orthogonal array. 

The function should provide OAs for ncol <= 2*(q^exponent-1)/(q-1) - 1 (not documented, but appropriately implemented with this limitation, in line with Theorem 3.16 of Hedayat, Sloane and Stufken 1999). If I request so many factors, I get unwarned non-orthogonality, however:

`A <- createAddelKempN(3, 25, 3, TRUE)`
`table(A[,1], A[,5])`

yields the unbalanced result (edited) 

`_____   A[,5]`
`A[,1] 0 1 2`
` ___ 0 9 9 0`
` ___ 1 9 0 9`
` ___ 2 0 9 9`

Function `DoE.base::GWLP` shows that there are 25 words of length 2 (with contribution 0.5 from the tabulated pair A[,1] and A[,5]). I have not tried to locate the root cause of the problem. 

Kind regards,
Ulrike

**Comment by bertcarnell** [comment]
Ulrike, 

Thank you very much for the bug report.  I can reproduce it.  This is caused by an unfortunate translation error from Owen's original code.  I even had a note in the source code to revisit this, but failed to!  I am writing tests now and hope to have it republished here soon, and then to CRAN shortly thereafter.  As you probably know, reverse dependency checks have become the most difficult part of publishing a package.    

Rob

**Comment by bertcarnell** [comment]
This is fixed in https://github.com/bertcarnell/lhs/commit/2b000370b7972a7218ea99670f3ea86fabbe58f6.

**Comment by ugroempi** [comment]
Thanks, Rob!
